version: "3.9"
services:
  genesys-audiohook-collector:
    build: 
      context: .
      dockerfile: containerization.dockerfile
    restart: unless-stopped
    environment:
      GENESYS_ENV: "usw2.pure.cloud"
      GENESYS_CLIENT_ID: "${GENESYS_CLIENT_ID}"
      GENESYS_CLIENT_SECRET: "${GENESYS_CLIENT_SECRET}"
      
      OUTPUT_FILE: "/app/data/audiohook_events.jsonl"
      CONSOLE_OUTPUT: "true"
      
      # Optional Elasticsearch integration
      ELASTIC_URL: "${ELASTIC_URL:-}"
      ELASTIC_AUTH: "${ELASTIC_AUTH:-}"
      ELASTIC_INDEX: "genesys-audiohook"
      
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8077"
      
      TOPICS_FILE: "/app/topics.json"
    
    volumes:
      - ./data:/app/data
    
    ports:
      - "8077:8077"
    
    logging:
      options:
        max-size: "10m"
        max-file: "5"
