### BEGIN: docker-compose.yml
version: "3.9"
services:
  genesys-notif-collector:
    build: .
    restart: unless-stopped
    environment:
      GENESYS_ENV: "usw2.pure.cloud"
      GENESYS_CLIENT_ID: "${GENESYS_CLIENT_ID}"
      GENESYS_CLIENT_SECRET: "${GENESYS_CLIENT_SECRET}"
      TOPICS_FILE: "/app/topics.json"

      ELASTIC_URL: "${ELASTIC_URL}"
      ELASTIC_AUTH: "${ELASTIC_AUTH}"           # "user:pass" or a Bearer token
      ELASTIC_DATASTREAM: "false"               # set true if using data stream
      ELASTIC_INDEX: "genesys-events"           # data stream name or index base

      BULK_MAX_DOCS: "200"
      BULK_MAX_SECONDS: "5"
      BULK_CONCURRENCY: "2"
    logging:
      options:
        max-size: "10m"
        max-file: "5"
### END: docker-compose.yml
